server:
  port: 8080
spring:
  application:
#    应用名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    比如表名：user_name  对应的实体命名为 userName
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  path: E:\mavenbprojects\img\






##Redis服务器地址
#  spring.redis.host=192.168.147.128
#  #Redis服务器连接端口
#  spring.redis.port=6379
#  #Redis数据库索引（默认为0）
#  spring.redis.database= 0
#  #连接超时时间（毫秒）
#  spring.redis.timeout=1800000
#  #连接池最大连接数（使用负值表示没有限制）
#  spring.redis.lettuce.pool.max-active=20
#  #最大阻塞等待时间(负数表示没限制)
#  spring.redis.lettuce.pool.max-wait=-1
#  #连接池中的最大空闲连接
#  spring.redis.lettuce.pool.max-idle=5
#  #连接池中的最小空闲连接
#  spring.redis.lettuce.pool.min-idle=0